# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# # Add steps that build, run tests, deploy, and more:
# # https://aka.ms/yaml

trigger:
 - main

pool:
   vmImage: ubuntu-latest

variables: 
    acrserviceconnection: cred-acr
    tag: '(Build.BuildId)'
    forntendrepo: 'credpay/frontend'
    paymentrepo: 'credpay/payment'
    userrepo: 'credpay/user'
stages:
  - stage: DockerBuild
    displayName: Build Docker Images
    jobs:
      - job: BuildAndPublishImages
        displayName: Build Docker Images
        steps:
          - checkout: self
